### ISSUE TITLE
Current build fails

### ISSUE THREAD

**Issue by maxice8** [DataDrake/cuppa#14] opened 2019-04-23 19:57 UTC
Trying to package it for alpine using upstream instructions leads to.

```
 ⮞  16:56:27  BUILD  
cuppa.go:20:2: cannot find package "github.com/DataDrake/cuppa/cli" in any of:
	/usr/lib/go/src/github.com/DataDrake/cuppa/cli (from $GOROOT)
	/home/impreza/usr/src/aports/testing/cuppa/src/src/github.com/DataDrake/cuppa/cli (from $GOPATH)
make: *** [Makefile:29: build] Error 1
>>> ERROR: cuppa: build failed
```

**Comment by DataDrake** [comment] 2019-04-23 20:06
I can't reproduce this. Are you building from master or a tagged release? v1.0.4 is broken and I need to tweak a few things before I release v1.1.0.

**Comment by maxice8** [comment] 2019-04-23 20:08
building from current commit  that is in master

**Comment by DataDrake** [comment] 2019-04-23 20:11
Can you try with GOPATH cleared and let me know what version of Go you are using?

**Comment by DataDrake** [comment] 2020-06-23 16:45
I'm going to close this since I've waited over a year for an answer.

**Closed by DataDrake** 2020-06-23 16:45 UTC
